### ISSUE TITLE
Allow extension of categories without having to recompile

### ISSUE THREAD

**Issue by umlaeute** [raspberrypi-ui/rp-prefapps#8]
It's pretty easy to extend the recommended applications by adding a new 
```
[Package42]
name=Yummy
package=yummy
category=Other
description=Yummy yummy :-P
icon=yummy

```

stanza to the `prefapps.conf` file.

it is also possible to add a new category (e.g. by using `category=YummyApps`).
Unfortunately this new category will show up with an empty icon.

This is because the mapping from category name to icon is hardcoded in `cat_icon_name` (and any unknown categories fall back to `NULL`):
https://github.com/raspberrypi-ui/rp-prefapps/blob/eae5e7c32a50ecfd46d23783a9072045b9e31b5f/src/rp_prefapps.c#L1111-L1114

it would be great if you could get rid of the hardcoded mapping and allow for extending the categories at runtime.

a simple approach would be to just return the category name itself, if there is no match in the predefined list (TODO: check how this works with i18n):

```C
 if (!g_strcmp0 (category, N_("Universal Access"))) 
     return "preferences-desktop-accessibility"; 
  
 return category; 
```

alternatively, there could be a configuration file to define (additional categories) and their mapping to icons:

```ini
[Category01]
name=YummyApps
icon=yummy-apps
description=Assorted apps with taste
```

**Comment by spl237** [comment]
rp-prefapps is not intended to be customised by end-users - it is purely for us to distribute our own recommended software.

**Comment by umlaeute** [comment]
while i'm aware of that, i find it a bit sad.
