### ISSUE TITLE
easily extendible configuration

### ISSUE THREAD

**Issue by umlaeute** [raspberrypi-ui/rp-prefapps#9]
currently the configuration of `rp-prefapps` lives in in a single file `/usr/share/rp-prefapps/prefapps.conf`.

Adding new recommended software requires that this file is modified, which is not very extensible (that is: it's hard to add new recommended software by installing a "yummyapps-recommender" package).

it would be nice if `rp-prefapps` would also read all `/usr/share/rp-prefapps/packages.conf.d/*.conf` files.

(i'm aware that you probably do not really want the recommendations to be easily extendible; but still...)

**Comment by spl237** [comment]
As other issue - this application is not designed to be extensible by users.

**Comment by umlaeute** [comment]
that's a pity.

&lt;rant>
good for you that Debian does care for their downstreams.
&lt;/rant>

:shrug:
